spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: testpassword

  jpa:
    hibernate:dialect: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9191